trigger:
- master

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  displayName: 'Build Horion'
  inputs:
    solution: '$(Parameters.solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64
- task: PublishPipelineArtifact@1
  displayName: 'Publish Horion.dll'
  inputs:
    targetPath: 'd:\a\1\s\x64\Release\Horion.dll'
    artifact: Horion